Vignette: minimisation vs block and simple randomization
ttscience/unbiased pull request #39
Opened 2024-01-25 16:39 UTC by kamilsi

This closes #33

2024-01-26 15:32 UTC, lwalejko requested changes

2024-01-26 15:32 UTC, lwalejko commented on vignettes/simulations.Rmd
> +      local_df <- strata_grid %>%
Could you use `|>` pipe?

2024-01-26 15:32 UTC, lwalejko commented on vignettes/simulations.Rmd
> +  ) %>%
Could you use `|>` pipe?

2024-01-26 15:32 UTC, lwalejko commented on vignettes/simulations.Rmd
> +  simulation_result <-
you can make this a function instead and generate randomization table on demand to conserve memory

2024-01-26 16:27 UTC, kamilsi reviewed
Great work on this document, Ola! You've done a fantastic job in laying out the details of the simulation. I've included a few suggestions to further refine and clarify some points. Your effort in putting this together really shows, and these minor adjustments are just to enhance what is already a solid piece of work. Keep up the great effort!

2024-01-26 16:27 UTC, kamilsi commented on vignettes/simulations.Rmd
> +    "beta",
I think you loose the `row tibble` advantage when you break the rows like this :-)

2024-01-26 16:27 UTC, kamilsi commented on vignettes/simulations.Rmd
> +```
Let's skip this stem entirely and do simple Monte Carlo

2024-01-26 16:27 UTC, kamilsi commented on vignettes/simulations.Rmd
> +          formula = "(diabetes_type==0) * (-3.5)",
you can skip comparison and do something like `diabetes_type * 3.5` IMO

2024-01-26 16:27 UTC, kamilsi commented on vignettes/simulations.Rmd
> +On the other hand, block randomization performs very well in balancing the number of patients in groups in a specified allocation ratio. However, its effect size power is lower for covariate balance
What do you mean "effect size power"?

2024-01-30 10:08 UTC, aleksandraduda2 commented on vignettes/simulations.Rmd
> +}
right suggestion

2024-02-08 10:27 UTC, JagGlo approved these changes
Great work, Ola! This chunk of text you prepared is really impressive!
Plus: Vignette has now became an article.

2024-02-08 11:38 UTC, lwalejko approved these changes

2024-02-09 11:29 UTC, merged